server.port: 8888
spring:
  application:
    name: config-service
  profiles:
    active: native

#  cloud:
#    config:
#      server:
#        git:
#          skip-ssl-validation: true
#          uri: https://github.com/AndZPW/note-app-configs.git
#          username: AndZWP
#          password: s6inwc5hv59v5x9
#          default-label: main
#spring.cloud.config.server.native.searchLocations="{application}"
